const pipelineState = {
    status: "Idle", 
    pipelineId: null,
    currentStage: null,
    currentCompany: null,
    activeCompanies: [],
    progress: "",
    elapsedTime: 0,
    estimatedRemainingTime: 0,
    currentAiProvider: null,
    lastRunDuration: 0,
    jobsScraped: 0,
    jobsEvaluated: 0,
    jobsMatched: 0,
    lastRunTime: null,
    nextRunTime: null,
    message: "",
    geminiStatus: "Ready",
    geminiReason: null,
    geminiRequests: 0,
    geminiSuccess: 0,
    geminiFailed: 0,
    geminiFallbacks: 0,
    geminiDisabledAt: null,
    geminiNextRetry: null,
    groqStatus: "Ready",
    groqReason: null,
    groqRequests: 0,
    groqSuccess: 0,
    groqFailed: 0,
    groqFallbacks: 0,
    groqDisabledAt: null,
    groqNextRetry: null,
    zaiStatus: "Ready",
    zaiReason: null,
    zaiRequests: 0,
    zaiSuccess: 0,
    zaiFailed: 0,
    zaiFallbacks: 0,
    zaiDisabledAt: null,
    zaiNextRetry: null,
    localStatus: "Ready",
    localRequests: 0,
    localSuccess: 0,
    localFailed: 0
};

module.exports = pipelineState;
