// For now the project uses only API-based scraping.
// This keeps the code easier to understand and easier to explain in a resume.
module.exports = [
    {
        name: "CommerceIQ",
        category: "Product",
        active: true,
        careerUrl: "https://job-boards.greenhouse.io/commerceiq",
        scraperType: "api",
        scraperConfig: {
            strategy: "greenhouse",
            apiUrl: "https://boards-api.greenhouse.io/v1/boards/commerceiq/jobs",
            limit: 100,
            allowedLocations: [
                "india",
                "bengaluru",
                "bangalore",
                "remote",
            ],
            targetKeywords: [
                "software development engineer",
                "software engineer",
                "backend",
                "server side",
                "api",
                "java",
                "python",
                "spring boot",
                "dsa",
            ],
            excludedKeywords: [
                "engineer ii",
                "engineer iii",
                "senior",
                "staff",
                "principal",
                "manager",
                "director",
                "1-3",
                "1 to 3",
                "2+",
                "3+",
            ],
        },
    },
    {
    name: "Visa",
    category: "Product",
    active: true,

    careerUrl:
        "https://visa.wd5.myworkdayjobs.com/en-US/Visa",

    scraperType: "api",

        scraperConfig: {
            strategy: "workday",

        apiUrl:
            "https://visa.wd5.myworkdayjobs.com/wday/cxs/visa/Visa/jobs",

        limit: 20,
        allowedLocations: [
            "india",
            "remote",
            "bengaluru",
            "bangalore",
        ],
        targetKeywords: [
            "software engineer",
            "software development engineer",
            "sde",
            "backend",
            "developer",
            "api",
        ],
        excludedKeywords: [
            "senior",
            "sr ",
            "sr.",
            "staff",
            "principal",
            "manager",
            "director",
            "lead",
            "1-3",
            "1 to 3",
            "2+",
            "3+",
        ],
    }
},
    {
        name: "LG",
        category: "Product",
        active: true,
        careerUrl: "https://globalcareers.lge.com/jobs",
        scraperType: "api",

        // LG also has an API, but its JSON shape is different from Visa.
        // The "lg" strategy tells scraperService to use the LG-specific mapper.
        scraperConfig: {
            strategy: "lg",
            apiUrl: "https://globalcareers.lge.com/api/job/v1/jobs/",
            limit: 50,
            allowedLocations: [
                "india",
                "remote",
                "bengaluru",
                "bangalore",
                "noida",
            ],
            targetKeywords: [
                "software engineer",
                "software development engineer",
                "backend",
                "developer",
                "api",
                "node",
                "java",
                "python",
            ],
            excludedKeywords: [
                "senior",
                "sr ",
                "sr.",
                "embedded",
                "staff",
                "principal",
                "manager",
                "director",
                "lead",
                "1-3",
                "1 to 3",
                "2+",
                "3+",
            ],
        },
    },
    {
        name: "Adobe",
        category: "Product",
        active: true,
        careerUrl: "https://adobe.wd5.myworkdayjobs.com/en-US/external_experienced",
        scraperType: "api",
        scraperConfig: {
            strategy: "workday",
            apiUrl: "https://adobe.wd5.myworkdayjobs.com/wday/cxs/adobe/external_experienced/jobs",
            limit: 20,
            allowedLocations: [
                "india",
                "remote",
                "bengaluru",
                "bangalore",
                "noida",
            ],
            targetKeywords: [
                "software engineer",
                "software development engineer",
                "sde",
                "backend",
                "developer",
                "api",
            ],
            excludedKeywords: [
                "senior",
                "sr ",
                "sr.",
                "staff",
                "principal",
                "manager",
                "director",
                "lead",
                "1-3",
                "1 to 3",
                "2+",
                "3+",
            ],
        },
    },
    {
        name: "Paytm",
        category: "Product",
        active: true,
        careerUrl: "https://jobs.lever.co/paytm",
        scraperType: "api",
        scraperConfig: {
            strategy: "lever",
            apiUrl: "https://api.lever.co/v0/postings/paytm",
            allowedLocations: [
                "india",
                "remote",
                "bengaluru",
                "bangalore",
                "noida",
                "hyderabad",
                "pune",
            ],
            targetKeywords: [
                "software engineer",
                "software development engineer",
                "sde",
                "backend",
                "developer",
                "api",
                "node",
                "java",
                "python",
            ],
            excludedKeywords: [
                "senior",
                "sr ",
                "sr.",
                "staff",
                "principal",
                "manager",
                "director",
                "lead",
                "architect",
                "1-3",
                "1 to 3",
                "2+",
                "3+",
            ],
        },
    },
    {
        name: "PhonePe",
        category: "Product",
        active: true,
        careerUrl: "https://job-boards.greenhouse.io/phonepe",
        scraperType: "api",
        scraperConfig: {
            strategy: "greenhouse",
            apiUrl: "https://boards-api.greenhouse.io/v1/boards/phonepe/jobs",
            allowedLocations: [
                "india",
                "remote",
                "bengaluru",
                "bangalore",
                "pune",
            ],
            targetKeywords: [
                "software engineer",
                "software development engineer",
                "sde",
                "backend",
                "developer",
                "api",
                "java",
                "python",
            ],
            excludedKeywords: [
                "engineering manager",
                "senior",
                "sr ",
                "sr.",
                "android",
                "ios",
                "mobile",
                "staff",
                "principal",
                "manager",
                "director",
                "lead",
                "head",
                "architect",
                "1-3",
                "1 to 3",
                "2+",
                "3+",
            ],
        },
    },
    {
        name: "Groww",
        category: "Product",
        active: true,
        careerUrl: "https://job-boards.greenhouse.io/groww",
        scraperType: "api",
        scraperConfig: {
            strategy: "greenhouse",
            apiUrl: "https://boards-api.greenhouse.io/v1/boards/groww/jobs",
            allowedLocations: [
                "india",
                "bengaluru",
                "bangalore",
            ],
            targetKeywords: [
                "software engineer",
                "software development engineer",
                "sde",
                "backend",
                "developer",
                "api",
                "node",
                "java",
                "python",
            ],
            excludedKeywords: [
                "senior",
                "sr ",
                "sr.",
                "staff",
                "principal",
                "manager",
                "director",
                "lead",
                "architect",
                "content",
                "marketing",
                "growth",
                "design",
                "designer",
                "graphic",
                "video",
                "editor",
                "copy writer",
                "1-3",
                "1 to 3",
                "2+",
                "3+",
            ],
        },
    },
    {
        name: "InMobi",
        category: "Product",
        active: true,
        careerUrl: "https://job-boards.greenhouse.io/inmobi",
        scraperType: "api",
        scraperConfig: {
            strategy: "greenhouse",
            apiUrl: "https://boards-api.greenhouse.io/v1/boards/inmobi/jobs",
            allowedLocations: [
                "india",
                "bengaluru",
                "bangalore",
            ],
            targetKeywords: [
                "software engineer",
                "software development engineer",
                "sde",
                "backend",
                "developer",
                "api",
                "java",
                "python",
                "node",
            ],
            excludedKeywords: [
                "senior",
                "sr ",
                "sr.",
                "staff",
                "principal",
                "manager",
                "director",
                "lead",
                "architect",
                "product manager",
                "salesforce",
                "1-3",
                "1 to 3",
                "2+",
                "3+",
            ],
        },
    },
    {
        name: "Tekion",
        category: "Product",
        active: true,
        careerUrl: "https://job-boards.greenhouse.io/tekion",
        scraperType: "api",
        scraperConfig: {
            strategy: "greenhouse",
            apiUrl: "https://boards-api.greenhouse.io/v1/boards/tekion/jobs",
            allowedLocations: [
                "india",
                "bengaluru",
                "bangalore",
            ],
            targetKeywords: [
                "software engineer",
                "software development engineer",
                "sde",
                "backend",
                "developer",
                "api",
                "java",
                "python",
                "node",
            ],
            excludedKeywords: [
                "senior",
                "sr ",
                "sr.",
                "staff",
                "principal",
                "manager",
                "director",
                "lead",
                "architect",
                "frontend",
                "android",
                "ios",
                "mobile",
                "1-3",
                "1 to 3",
                "2+",
                "3+",
            ],
        },
    },
    {
        name: "Thoughtworks",
        category: "Service",
        active: true,
        careerUrl: "https://job-boards.greenhouse.io/thoughtworks",
        scraperType: "api",
        scraperConfig: {
            strategy: "greenhouse",
            apiUrl: "https://boards-api.greenhouse.io/v1/boards/thoughtworks/jobs",
            allowedLocations: [
                "india",
                "bengaluru",
                "bangalore",
                "pune",
                "chennai",
                "hyderabad",
                "gurgaon",
                "noida",
            ],
            targetKeywords: [
                "graduate developer",
                "associate developer",
                "software developer",
                "developer",
                "software engineer",
                "backend",
                "java",
                "python",
                "node",
            ],
            excludedKeywords: [
                "senior",
                "sr ",
                "sr.",
                "staff",
                "principal",
                "manager",
                "director",
                "lead",
                "architect",
                "consultant",
                "1-3",
                "1 to 3",
                "2+",
                "3+",
            ],
        },
    },
    {
        name: "Nagarro",
        category: "Service",
        active: true,
        careerUrl: "https://jobs.smartrecruiters.com/Nagarro1",
        scraperType: "api",
        scraperConfig: {
            strategy: "smartrecruiters",
            apiUrl: "https://api.smartrecruiters.com/v1/companies/Nagarro1/postings",
            limit: 100,
            params: {
                search: "software",
            },
            allowedLocations: [
                "india",
                "bengaluru",
                "bangalore",
                "pune",
                "gurgaon",
                "noida",
                "hyderabad",
            ],
            targetKeywords: [
                "software engineer",
                "software developer",
                "backend",
                "developer",
                "api",
                "java",
                "python",
                "node",
            ],
            excludedKeywords: [
                "senior",
                "sr ",
                "sr.",
                "staff",
                "principal",
                "associate principal",
                "manager",
                "director",
                "lead",
                "architect",
                "frontend",
                "data science",
                "machine learning",
                "1-3",
                "1 to 3",
                "2+",
                "3+",
            ],
        },
    },
    {
        name: "Razorpay",
        category: "Product",
        active: true,
        careerUrl: "https://job-boards.greenhouse.io/razorpaysoftwareprivatelimited",
        scraperType: "api",
        scraperConfig: {
            strategy: "greenhouse",
            apiUrl: "https://boards-api.greenhouse.io/v1/boards/razorpaysoftwareprivatelimited/jobs",
            allowedLocations: [
                "india",
                "bengaluru",
                "bangalore",
                "mumbai",
                "hyderabad",
            ],
            targetKeywords: [
                "software engineer",
                "software development engineer",
                "sde",
                "backend",
                "developer",
                "api",
                "java",
                "python",
                "node",
            ],
            excludedKeywords: [
                "senior",
                "sr ",
                "sr.",
                "staff",
                "principal",
                "manager",
                "director",
                "lead",
                "architect",
                "sales",
                "operations",
                "banking",
                "growth",
                "1-3",
                "1 to 3",
                "2+",
                "3+",
            ],
        },
    },
    {
        name: "MongoDB",
        category: "Product",
        active: true,
        careerUrl: "https://job-boards.greenhouse.io/mongodb",
        scraperType: "api",
        scraperConfig: {
            strategy: "greenhouse",
            apiUrl: "https://boards-api.greenhouse.io/v1/boards/mongodb/jobs",
            allowedLocations: [
                "india",
                "bengaluru",
                "bangalore",
                "gurugram",
                "hyderabad",
                "pune",
            ],
            targetKeywords: [
                "software engineer",
                "backend",
                "developer",
                "api",
                "java",
                "python",
                "node",
            ],
            excludedKeywords: [
                "senior",
                "sr ",
                "sr.",
                "staff",
                "principal",
                "manager",
                "director",
                "lead",
                "architect",
                "sales",
                "account",
                "recruiter",
                "support",
                "1-3",
                "1 to 3",
                "2+",
                "3+",
            ],
        },
    },
    {
        name: "GitLab",
        category: "Product",
        active: true,
        careerUrl: "https://job-boards.greenhouse.io/gitlab",
        scraperType: "api",
        scraperConfig: {
            strategy: "greenhouse",
            apiUrl: "https://boards-api.greenhouse.io/v1/boards/gitlab/jobs",
            allowedLocations: [
                "india",
                "remote, india",
                "remote - india",
            ],
            targetKeywords: [
                "backend engineer",
                "software engineer",
                "developer",
                "api",
                "golang",
                "ruby",
                "python",
                "node",
            ],
            excludedKeywords: [
                "senior",
                "sr ",
                "sr.",
                "staff",
                "principal",
                "manager",
                "director",
                "lead",
                "architect",
                "customer success",
                "solutions",
                "sales",
                "1-3",
                "1 to 3",
                "2+",
                "3+",
            ],
        },
    },
    {
        name: "Postman",
        category: "Product",
        active: true,
        careerUrl: "https://job-boards.greenhouse.io/postman",
        scraperType: "api",
        scraperConfig: {
            strategy: "greenhouse",
            apiUrl: "https://boards-api.greenhouse.io/v1/boards/postman/jobs",
            allowedLocations: [
                "india",
                "bengaluru",
                "bangalore",
                "remote, india",
                "remote - india",
            ],
            targetKeywords: [
                "backend",
                "system engineer",
                "software engineer",
                "developer",
                "api",
                "node",
                "golang",
                "java",
            ],
            excludedKeywords: [
                "senior",
                "sr ",
                "sr.",
                "staff",
                "principal",
                "manager",
                "director",
                "lead",
                "architect",
                "frontend",
                "frontend-heavy",
                "fullstack",
                "solutions engineer",
                "customer success",
                "sales",
                "1-3",
                "1 to 3",
                "2+",
                "3+",
            ],
        },
    },
    {
        name: "Databricks",
        category: "Product",
        active: true,
        careerUrl: "https://job-boards.greenhouse.io/databricks",
        scraperType: "api",
        scraperConfig: {
            strategy: "greenhouse",
            apiUrl: "https://boards-api.greenhouse.io/v1/boards/databricks/jobs",
            allowedLocations: [
                "india",
                "remote - india",
                "remote, india",
                "bengaluru",
                "bangalore",
            ],
            targetKeywords: [
                "software engineer",
                "backend",
                "developer",
                "api",
                "python",
                "java",
                "scala",
            ],
            excludedKeywords: [
                "senior",
                "sr ",
                "sr.",
                "staff",
                "principal",
                "manager",
                "director",
                "lead",
                "architect",
                "forward deployed",
                "solutions",
                "sales",
                "1-3",
                "1 to 3",
                "2+",
                "3+",
            ],
        },
    },
    {
        name: "Zeta",
        category: "Product",
        active: true,
        careerUrl: "https://jobs.lever.co/zeta",
        scraperType: "api",
        scraperConfig: {
            strategy: "lever",
            apiUrl: "https://api.lever.co/v0/postings/zeta",
            allowedLocations: [
                "india",
                "bangalore",
                "bengaluru",
                "mumbai",
                "hyderabad",
            ],
            targetKeywords: [
                "software engineer",
                "software developer",
                "backend",
                "developer",
                "api",
                "java",
                "python",
                "node",
            ],
            excludedKeywords: [
                "senior",
                "sr ",
                "sr.",
                "staff",
                "principal",
                "manager",
                "director",
                "lead",
                "architect",
                "operations",
                "payroll",
                "compliance",
                "sales",
                "1-3",
                "1 to 3",
                "2+",
                "3+",
            ],
        },
    },
];
